easy_admin:
    design:
        assets:
            css:
                - '/public/assets/css/easyadmin.css'
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation
  